# Generated by Django 4.0.3 on 2022-03-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Cast_name')),
            ],
        ),
        migrations.CreateModel(
            name='SoundSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(db_index=True, max_length=300)),
                ('artist_type', models.CharField(db_index=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Writer_name')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Movie Title')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4, max_length=500, verbose_name='Rating')),
                ('duration', models.CharField(max_length=200, verbose_name='Duration')),
                ('director', models.CharField(max_length=500, verbose_name='Director')),
                ('img_link', models.CharField(max_length=400, verbose_name='Image Link')),
                ('year', models.CharField(max_length=500, verbose_name='Year')),
                ('producer', models.CharField(max_length=200, verbose_name='Producer')),
                ('musician', models.CharField(max_length=200, verbose_name='Musician')),
                ('cast', models.ManyToManyField(to='movie_website.cast')),
                ('writers', models.ManyToManyField(to='movie_website.writer')),
            ],
        ),
    ]
