# Generated by Django 4.0.3 on 2022-03-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Director_name')),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Musician_name')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Producer_name')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='image_url',
            field=models.CharField(default='', max_length=1000, verbose_name='Image Link'),
        ),
        migrations.AddField(
            model_name='movie',
            name='sounds',
            field=models.ManyToManyField(to='movie_website.soundsection'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='musician',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='producer',
        ),
        migrations.AlterField(
            model_name='soundsection',
            name='artist_type',
            field=models.CharField(max_length=300),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(to='movie_website.director'),
        ),
        migrations.AddField(
            model_name='movie',
            name='musician',
            field=models.ManyToManyField(to='movie_website.musician'),
        ),
        migrations.AddField(
            model_name='movie',
            name='producer',
            field=models.ManyToManyField(to='movie_website.producer'),
        ),
    ]
