# Generated by Django 4.0.3 on 2022-03-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_website', '0002_director_musician_producer_movie_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='movie_website.director'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='movie',
            name='producer',
        ),
        migrations.AddField(
            model_name='movie',
            name='producer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='movie_website.producer'),
            preserve_default=False,
        ),
    ]
