# Generated by Django 4.0.3 on 2022-03-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_website', '0003_remove_movie_director_movie_director_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='img_link',
        ),
    ]
