# Generated by Django 4.0.3 on 2022-03-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_website', '0004_remove_movie_img_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Genre_name')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='movie_website.genre'),
        ),
    ]
