# Generated by Django 4.0.3 on 2022-03-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_website', '0005_genre_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Description'),
        ),
    ]
