# Generated by Django 4.0.3 on 2022-03-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_website', '0006_alter_movie_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(to='movie_website.director'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='producer',
        ),
        migrations.AddField(
            model_name='movie',
            name='producer',
            field=models.ManyToManyField(to='movie_website.producer'),
        ),
    ]
