# Generated by Django 4.0.3 on 2022-03-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_website', '0008_alter_movie_cast_alter_movie_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(to='movie_website.cast'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(to='movie_website.director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='movie_website.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='musician',
            field=models.ManyToManyField(to='movie_website.musician'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='producer',
            field=models.ManyToManyField(to='movie_website.producer'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='sounds',
            field=models.ManyToManyField(blank=True, null=True, to='movie_website.soundsection'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='writers',
            field=models.ManyToManyField(to='movie_website.writer'),
        ),
    ]
