# Generated by Django 4.0.3 on 2022-03-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_website', '0009_alter_movie_cast_alter_movie_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='sounds',
            field=models.ManyToManyField(blank=True, to='movie_website.soundsection'),
        ),
    ]
