# Generated by Django 4.0.3 on 2022-03-11 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_website', '0010_alter_movie_sounds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writer',
            old_name='name',
            new_name='writer_name',
        ),
    ]
