# Generated by Django 4.0.3 on 2022-03-11 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_website', '0011_rename_name_writer_writer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writer',
            old_name='writer_name',
            new_name='name',
        ),
    ]
