# Generated by Django 4.0.3 on 2022-03-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_website', '0013_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='', upload_to='avatar'),
        ),
    ]
