# Generated by Django 4.0.3 on 2022-03-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_website', '0014_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='', upload_to='avatar', verbose_name='avatar'),
        ),
    ]
