# Generated by Django 4.0.3 on 2022-03-29 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_website', '0015_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100, verbose_name='Movie Name')),
                ('order_date', models.DateField()),
                ('order_status', models.CharField(max_length=100, verbose_name='status')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_website.user')),
            ],
        ),
    ]
